BotSelfConfig:
  host: "127.0.0.1"
  port: 8080
  debug: false
  superusers: ["2946044189"]
  nickname: ["锦力"]
  command_start: ["", "/"]
  command_sep: ["."]
  session_expire_timeout: 60
  proxy: ""  # 请参考文档

InlineGoCQHTTP:
  enabled: true
  accounts: # 可多个账号，具体请参考文档
    - uin: 3315467625
      password: "31415926yzl"
      protocol: 5
  
  download_domain: "github.com"
  download_version: "v1.0.0-rc1"

SauceNAO:
  key: "9a61b0d3f0f4986c0753eb1c45919b0b76934188"

Setu:
  reverse_proxy: true # 请参考文档
  reverse_proxy_domain: "i.pixiv.re"
